version: "3.8"
services:
  neo4j:
    image: neo4j:5.23
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/default1
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_PLUGINS=["apoc","apoc-extended","graph-data-science"]
    volumes:
      - ../qcpg/src/main/resources/volumes/neo4j/data:/data
      - ../qcpg/src/main/resources/volumes/neo4j/logs:/logs
      - ../qcpg/src/main/resources/volumes/neo4j/import:/var/lib/neo4j/import
      - ../qcpg/src/main/resources/volumes/neo4j/plugins:/plugins
