version: "3.9"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra
    volumes:
      - cassandra_data:/var/lib/cassandra
    
    neo4j:
    image: neo4j:5.16.0-community-bullseye
    container_name: neo4j-container
    environment:
      NEO4J_AUTH: neo4j/default1 # Password must be 8+ characters
    ports:
      - "7474:7474"
      - "7687:7687"
