spring:
  application:
    name: qcpg

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: default1

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG

